export const SEARCH_FLIGHTS_DATA = "SEARCH_FLIGHTS_DATA";
export const MANAGE_AIRLINE_DATA = "MANAGE_AIRLINE_DATA";
export const ADD_AIRLINE = "ADD_AIRLINE";
export const NO_FLIGHTS_FOUND = "NO_FLIGHTS_FOUND";
