export const SEARCH_BY_VALUE = "SEARCH_BY_VALUE";
export const GET_ALL_BOOKINGS = "GET_ALL_BOOKINGS";
export const RESET_SEARCH_BY_VALUE = "RESET_SEARCH_BY_VALUE";
export const RESET_ALL_BOOKINGS = "RESET_ALL_BOOKINGS";
